### ISSUE TITLE
Doesn't find any devices

### ISSUE THREAD

**Issue by antonino-u** [stefanrenne/RxSonosLib#3]
Hey devs!
I'm struggling to understand ReactiveX, and I was wondering why this was the chosen as a technology.
Regardless of that, I'm wondering why the demo app doesn't seem to proceed past the initial search screen. It seems to not find any groups... for example, in `LoadingViewController` when `getAllGroups` is called, the array of groups within `filter` is empty. Not sure why... I have a fairly simple topology: a playbar and two play 1s. All are in different rooms and all are grouped together.

**Comment by stefanrenne** [comment]
Hi Antonino,

Thank you for your feedback!
- The reason for choosing RX is rather easy, I wanted to become better in using RX and as you can see in my commit history I have learned a lot.
- So the demo app, first things first, it's just a quick and really dirty implementation. What happens is that the moment the Loading view is presented it waits until their is at least one group. The first time the subscription returns an empty array because the SSDP (local network search for sonos devices) is not finished yet. The second time, which should be executed after 4 seconds it should return at least one group. in the latest release (0.10.0) I did change some stuff and apparently I broke the group searching when changing some classes into structs. This should be fixed in 0.11.0

**Comment by stefanrenne** [comment]
Just released 0.11.0 to cocoapods, thank you for your help!

**Comment by antonino-u** [comment]
Fixed! Thanks @stefanrenne!
